### PR TITLE
Client libraries as static modules

### LINKED ISSUE #3: Support the typesafe GraphQL client

### PR DESCRIPTION
**Pull request by jmartisk**
Fixes #3

### CODE REVIEW

**Comment by jmartisk** [comment]
@t1 thought you might want to have a look at this before I merge it.
This is the WildFly-preferred way to distribute the client libraries - their JARs will be included in the feature pack as static modules. A deployment which wants to use the client will have to declare a dependency on the module named `io.smallrye.graphql.client`.

The PR also changes the quickstart tests to use this approach. We could also transform this into a quickstart on its own, potentially, but I think this might be sufficient

**Comment by jmartisk** [comment]
@fmarchioni might also be interested in this, in-container clients can be slimmed down after this

**Comment by t1** [comment]
LGTM

**Comment by jmartisk** [comment]
If you have any questions just ask... I'm planning to soon introduce some short document describing how to properly deploy GraphQL server/client applications in WildFly. A quickstart alone might not be enough

**Pull request merged**
